USE [DoctorWho]
GO

/****** Object:  View [dbo].[vwEpisodesByFirstLetter]    Script Date: 04/12/2015 12:56:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW vwEpisodesByFirstLetter
AS

-- all this was generated by the view designer
SELECT TOP (100) PERCENT 
	a.AuthorName, 
	d.DoctorName, 
	e.Title, 
	e.EpisodeDate
FROM     
	tblAuthor AS a 
	INNER JOIN tblEpisode AS e ON a.AuthorId = e.AuthorId 
	INNER JOIN tblDoctor as d ON e.DoctorId = d.DoctorId
WHERE  

	-- change the first letter
	e.Title LIKE N'h%'
ORDER BY 
	e.EpisodeDate

GO

SELECT * FROM vwEpisodesByFirstLetter
GO


